# Generated by Django 5.0.7 on 2024-08-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_is_sale_product_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
